version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5001"
    depends_on:
      - db
      - cache
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      
  frontend:
      build: ./client-app
      ports:
        - "80:80"
      depends_on:
        - backend
        - cache
      environment:
        NODE_OPTIONS: "--openssl-legacy-provider"
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "zaq1@WSX"
      
  cache:
    image: redis